### ISSUE TITLE
Wants to connect

### ISSUE THREAD

**Issue by chengding0713** [zhahoi/YOLOv8P#1]
你好，我非常感兴趣你的工作，想和你合作。不知道是否能加个微信，我的wx是dc15105515112.

**Comment by zhahoi** [comment]
你好，我给你留一个我的邮箱吧，微信暂时不太方便。zhahoi@163.com。> 你好，我非常感兴趣你的工作，想和你合作。不知道是否能加个微信，我的wx是dc15105515112.
